# Generated by Django 5.2.17 on 2026-09-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="area",
            options={"ordering": ["order", "created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="goal",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="progressentry",
            options={"ordering": ["date", "created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["date", "created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["created_at", "id"]},
        ),
    ]
