# Generated by Django 5.2.17 on 2026-09-30 11:48

import django.db.models.deletion
import django.utils.timezone
import tracker.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_stable_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=tracker.models.new_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                ("focus", models.JSONField(default=list)),
                ("reflection", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["week_start"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="goal",
            name="goal_deadline_after_start",
        ),
        migrations.AddField(
            model_name="goal",
            name="days_per_week",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="kind",
            field=models.CharField(
                choices=[("target", "Target"), ("habit", "Habit")],
                default="target",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("deadline__isnull", True),
                    ("deadline__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="goal_deadline_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "target"),
                        ("deadline__isnull", False),
                        ("days_per_week__isnull", True),
                    ),
                    models.Q(
                        ("kind", "habit"),
                        ("deadline__isnull", True),
                        ("days_per_week__gte", 1),
                        ("days_per_week__lte", 7),
                    ),
                    _connector="OR",
                ),
                name="goal_kind_fields",
            ),
        ),
        migrations.AddField(
            model_name="weeklyreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weekly_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyreview",
            constraint=models.UniqueConstraint(
                fields=("user", "week_start"), name="weekly_review_one_per_week"
            ),
        ),
    ]
