# Generated by Django 5.2.17 on 2026-10-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_habits_and_weekly_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_open", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "настройки сервера",
                "verbose_name_plural": "настройки сервера",
            },
        ),
    ]
